### ISSUE TITLE
Update license header

### ISSUE THREAD

**Issue by krzikams** [levigo/jbig2-imageio#12]
Update LICENSE-HEADER.txt and run the maven with license:format.

**Comment by mattcg** [comment]
Thank you for all your work on this library, which has allowed us at ICIJ to save many months of work parsing images out of millions of PDFs.

Would you consider moving towards a license that's compatible with the Apache 2.0 license? The current license, GPLv3, prevents this library from being distributed with PDFBox[1], and therefore with Apache Tika. This seems to be restricting its use.

[1] https://pdfbox.apache.org/2.0/dependencies.html

**Comment by krzikams** [comment]
Contact us as described in https://github.com/levigo/jbig2-imageio/blob/master/README.md in the _License_ part
