### ISSUE TITLE
google code repository broken

### ISSUE THREAD

**Issue by THausherr** [levigo/jbig2-imageio#19]
https://code.google.com/archive/p/jbig2-imageio/

> Maven coordinates will work and need not to be changed

No, they don't work anymore, the repository is 404 now, so they must be changed: use the general repository, and version 1.6.5. Apparently older versions don't work anymore.  (I don't mind this, but it broke our build until I understood what happened).

**Comment by krzikams** [comment]
We'll close the googlecode project as it is read-only and changes are no more possible.

**Comment by krzikams** [comment]
In case the deletion is not possible, just ignore the old stuff. It is widely known, that googlecode was shut down. All services including maven repositories needs migration.
