### ISSUE TITLE
Huffman user tables in text regions

### ISSUE THREAD

**Issue by janpe2** [levigo/jbig2-imageio#26]
Huffman user tables do not work in TextRegion segments. Examples:
[jbig2.zip](https://github.com/levigo/jbig2-imageio/files/1056004/jbig2.zip)

If you open the JBIG2 files, you get:

```
ClassCastException: SymbolDictionary cannot be cast to Table
at TextRegion.getUserTable(TextRegion.java:826)
```

I'll create a pull request.

**Comment by hennejg** [comment]
Fixed in #28 / #35
