### ISSUE TITLE
Problems in standard Huffman tables

### ISSUE THREAD

**Issue by janpe2** [levigo/jbig2-imageio#27]
[jbig2_2.zip](https://github.com/levigo/jbig2-imageio/files/1056040/jbig2_2.zip)

If you open the image PDFjs_8145_p55.jb2, you get:
```
ArrayIndexOutOfBoundsException: -2147483604
at Bitmap.getByte(Bitmap.java:120)
```

The image unitized_page_ii.jb2 should contain some text but the decoding result is an empty page.

I have identified an issue in StandardTables.java that causes these problems. I'll create a pull request.

**Comment by hennejg** [comment]
Fixed in #29 / #36
