### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by 4F2E4A2E** [levigo/jbig2-imageio#5]
Hello guys!

Thank you for this lib, we are using it together with tess4j.
I would like to help you guys, to get jbig2-imageio to maven central.

Let me know if you are up to it.

Best regards

**Comment by krzikams** [comment]
Hi,

indeed we have the goal to move to maven central before the current maven repository hosted on googlecode will be shutdown.

In which way can you help to get jbig2-imageio to maven central?

Best regards

**Comment by 4F2E4A2E** [comment]
Great! Let's do it then. 
I have done it many times in the past and know all the steps needed. We could do it together in a teamviewer session or via mail. 

Best regards

**Comment by krzikams** [comment]
We have a process including deployment to Sonatypes OSS repository with a replication to Maven Central.

What basic steps do you take? Whats your concept?

**Comment by 4F2E4A2E** [comment]
I recommend to release only to maven central, to do so follow this guide: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by krzikams** [comment]
Ticket triggering repository creation:
https://issues.sonatype.org/browse/OSSRH-19659

**Comment by 4F2E4A2E** [comment]
Great! Thank you. http://search.maven.org/#artifactdetails%7Ccom.levigo.jbig2%7Clevigo-jbig2-imageio%7C1.6.5%7Cjar
