### ISSUE TITLE
JBig2 image writer

### ISSUE THREAD

**Issue by amischler** [levigo/jbig2-imageio#55]
In addition to my question posted on[ Software Recommendations.SE](https://softwarerecs.stackexchange.com/questions/48770/is-there-a-java-imageio-jbig2-image-writer), are there any plans to develop a JBig2 image writer allowing to encode JBig2 images using ImageIO/jbig2-imageio ?

**Comment by theMattCode** [comment]
The lib has been donated to Apache Foundation's pdfbox project. Please ask over there for some assistance. See the Readme for the link to its new home.
