### ISSUE TITLE
What does the files *.jb2 are

### ISSUE THREAD

**Issue by Mechtilde** [levigo/jbig2-imageio#57]
Hello,

I want to package this library for Debian because i need it as a dependency.

Can you provide the source for these files too?

src/test/resources/images/

**Comment by hennejg** [comment]
Please note that this project is no longer maintained, as it has been donated to the Apache Foundation and integrated into the PDFBox project. Yo can find the new source tree here: https://git-wip-us.apache.org/repos/asf?p=pdfbox-jbig2.git or here https://github.com/apache/pdfbox-jbig2.

**Comment by theMattCode** [comment]
The .jb2 are files compressed with the JBIG2 algorithms. Unit tests use them. They are not crucial for packaging the lib.
Btw, this lib is written in Java, which assures _write once, run everywhere_. Install a JVM and you're able to utilize the lib
Anyway, see apache's pdfbox repo which is the new home this lib.
