### ISSUE TITLE
Threading-Problem

### ISSUE THREAD

**Issue by FelixHermann** [levigo/jbig2-imageio#9]
Hello,

got a problem with the JBIG2-Plugin, with multiple-threads.

When I used it with 5 threads, all five threads were blocked after about one hour. All threads were locked in HashMap.getEntry()

Regards

Felix

**Comment by krzikams** [comment]
Hello Felix,

please provide more information. A stacktrace, threaddump and a test case would do it for the beginning.

Best regards,
M. Mayer

**Comment by FelixHermann** [comment]
Hello krzikams,

the problem occurrs, when I use PDFBox (https://pdfbox.apache.org/) with the JBIG2-plugin to convert PDF-files into Images. (using this method: org.apache.pdfbox.rendering.PDFRenderer.renderImageWithDPI)

Sorry, at the moment I cannot give you more information as the licence of my memory-profiler expired ... and I'm working on another project at the moment.

Regards

Felix

**Comment by krzikams** [comment]
Any updates here?
